name: My PHP Tests
on: [push, workflow_dispatch, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: "PHP${{matrix.php}} - Laravel${{matrix.laravel}}"
    strategy:
      fail-fast: true
      matrix:
          os: ['ubuntu-latest']
          php: [8.3]
          laravel: [11.*, 10.*]
          include:
              - laravel: 11.*
                testbench: 9.*
              - laravel: 10.*
                testbench: 8.*
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}          
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          tools: phpunit
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update

      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}

      - name: cat composer.lock
        run: cat ./composer.lock

      - name: run tests
        run: composer test